name: Linux

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'doc/**'

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - g++-12
          - clang++-15
        build_type: [Release]

    env:
      CXX: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get update
        sudo apt-get -y --no-upgrade install ${{ matrix.compiler }}
        sudo apt-get -y install libgtest-dev

    - run: cmake -E make_directory build

    - working-directory: build/
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        cmake --build .
        ctest --output-on-failure
