name: Linux

on: [push, pull_request]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - g++-9
          - g++-10
          - g++-11
          - clang++-10
          - clang++-11
          - clang++-12

        build_type: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      CXX: ${{ matrix.compiler }}

    steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.compiler }}
        sudo apt-get install -y libgtest-dev
    - uses: actions/checkout@v2
    - run: cmake -E make_directory build
    - working-directory: build/
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        cmake --build .
        ctest --output-on-failure

  linux-old:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - g++-7
          - g++-8
          - clang++-6.0
          - clang++-7
          - clang++-8
          - clang++-9
        build_type: [Release]

    runs-on: ubuntu-latest

    env:
      CXX: ${{ matrix.compiler }}

    steps:
    - run: |
        sudo apt-get update
        sudo apt-get -y --no-upgrade install ${{ matrix.compiler }}
        sudo apt-get -y install libgtest-dev
    - uses: actions/checkout@v2
    - run: cmake -E make_directory build
    - working-directory: build/
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        cmake --build .
        ctest --output-on-failure


